apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db
  labels:
    app: post-db
spec:
  selector:
    matchLabels:
      app: post-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
        - name: post-db
          image: mariadb:10.5
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'true'
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: post-db
            - mountPath: /docker-entrypoint-initdb.d
              name: post-initdb
          livenessProbe:
            exec:
              command: [ "mysqladmin", "ping" ]
          readinessProbe:
            exec:
              command: [ "mysql", "-h", "127.0.0.1", "-e", "SELECT 1" ]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: post-db
          persistentVolumeClaim:
            claimName: post-db
        - name: post-initdb
          configMap:
            name: post-initdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-initdb
  labels:
    app: post-db
data:
  initdb.sql: |
    create database if not exists posts;
    use posts;
    create table if not exists posts
    (
        id             bigint unsigned not null auto_increment primary key,
        uuid           varchar(36)     not null unique,
        user_id        bigint unsigned not null,
        title          varchar(255)    not null,
        content        text            not null,
        comments_count int unsigned    not null default 0,
        created_at     timestamp       not null default current_timestamp,
        updated_at     timestamp       not null default current_timestamp on update current_timestamp,
        deleted_at timestamp       null,
        index (user_id)
    );
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-db
  labels:
    app: post-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: post-db
  labels:
    app: post-db
spec:
  selector:
    app: post-db
  ports:
    - port: 3306
      targetPort: 3306
      appProtocol: mysql
